src/Entity/Child.php
<?php

namespace App\Entity;

use App\Repository\ChildRepository;
use Cocur\Slugify\Slugify;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * @ORM\Entity(repositoryClass=ChildRepository::class)
 */
class Child
{

    const SCHOOLAR_LEVEL = [
        0 => "levels.section.little",
        1 => "levels.section.middle",
        2 => "levels.section.big",
        3 => "levels.primary.one",
        4 => "levels.primary.two",
        5 => "levels.primary.three",
        6 => "levels.primary.four",
        7 => "levels.primary.five",
        8 => "levels.secondary.one",
        9 => "levels.secondary.two",
        10 => "levels.secondary.three",
        11 => "levels.secondary.four",
        12 => "levels.high.one",
        13 => "levels.high.two",
        14 => "levels.high.three",
    ];

    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;



    /**
     * @ORM\Column(type="integer")
     */
    private $schoolar_level;



    /**
     * @ORM\Column(type="date")
     */
    private $birthday_date;



    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="children")
     * @ORM\JoinColumn(nullable=false)
     */
    private $parent;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="users")
     * @ORM\JoinColumn(nullable=true)
     */
    private $school;

    /**
     * @ORM\Column(type="array")
     */
    private $events;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }



    public function getSchoolarLevel(): ?int
    {
        return $this->schoolar_level;
    }

    public function setSchoolarLevel(int $schoolar_level): self
    {
        $this->schoolar_level = $schoolar_level;

        return $this;
    }



    public function getBirthdayDate(): ?\DateTimeInterface
    {
        return $this->birthday_date;
    }

    public function setBirthdayDate(\DateTimeInterface $birthday_date): self
    {
        $this->birthday_date = $birthday_date;

        return $this;
    }

    public function getFormattedSchoolarLevel(): string
    {
        return self::SCHOOLAR_LEVEL[$this->schoolar_level];
    }



    public function getParent(): ?User
    {
        return $this->parent;
    }

    public function setParent(?User $parent): self
    {
        $this->parent = $parent;

        return $this;
    }

    public function getSchool(): ?User
    {
        return $this->school;
    }

    public function setSchool(?User $school): self
    {
        $this->school = $school;

        return $this;
    }

    public function getSlug() {
        $slug = new Slugify();
        return $slug->slugify($this->name);
    }

    public function getEvents(): ?array
    {
        return $this->events;
    }

    public function setEvents(array $events): self
    {
        $this->events = $events;

        return $this;
    }
    public function addEvent(int $event): self
    {

         array_push($this->events,$event);
        $this->events = array_unique($this->events);
        return $this;
    }



}

src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Cocur\Slugify\Slugify;
use DateTimeInterface;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass=UserRepository::class)
 * @UniqueEntity("email")
 */
class User extends AbstractLocalisation implements UserInterface
{


   /* const ROLES = [
        "roles.superadministrator" => ["ROLE_SUPER_ADMIN","ROLE_ADMIN","ROLE_MODERATOR"],
        "roles.administrator" => ["ROLE_ADMIN","ROLE_MODERATOR"],
        "roles.moderator" => ["ROLE_MODERATOR","ROLE_USER"] ,
        "roles.user" => ["ROLE_USER"],
    ];*/

    const ROLES = [
        "roles.superadministrator" => "ROLE_SUPER_ADMIN",
        "roles.administrator" => "ROLE_ADMIN",
        "roles.moderator" => "ROLE_MODERATOR" ,
        "roles.user" => "ROLE_USER",
    ];

    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     * @Assert\Email(
     *     message="user.type.emails"
     * )
     *
     */
    private $email;

    /**
     * @ORM\Column(type="json")
     */
    private $roles = [];

    /**
     * @ORM\Column(type="string", length=255)
     * @var string The hashed password
     * @Assert\NotCompromisedPassword(
     *     message="user.type.password.compromised"
     *  )
     */
    private $password;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Regex(
     *     pattern="/\d{9}/",
     *     message="user.type.regex.mobilephone"
     * )
     */
    private $mobile_phone;

    /**
     * @ORM\Column(type="date", nullable=true)
     */
    private $birthday_date;



    /**
     * @ORM\Column(type="string", length=255)
     *
     */
    private $name;

    /**
     * @ORM\Column(type="string", length=255,nullable=true)
     *
     */
    private $facebookID;

    /**
     * @ORM\Column(type="string", length=255,nullable=true)
     *
     */
    private $facebookToken;

    /**
     * @ORM\Column(type="integer")
     * @Assert\Type(
     *     type="integer",
     *     message="user.type.integer"
     * )
     */
    private $type;





    /**
     * @ORM\Column(type="string", length=255)
     */
    private $logo;


    /**
     * @ORM\OneToMany(targetEntity=Event::class, mappedBy="school")
     */
    private $events;

    /**
     * @ORM\OneToMany(targetEntity=Child::class, mappedBy="parent")
     */
    private $children;

    /**
     * @ORM\OneToMany(targetEntity=Child::class, mappedBy="school")
     */
    private $users;


    public function __construct()
    {




        $this->events = new ArrayCollection();
        $this->children = new ArrayCollection();
        $this->users = new ArrayCollection();
    }


    public function getId(): ?int
    {
        return $this->id;
    }

    /**
     *
     *
     * @see UserInterface
     */
    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }


    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUsername(): string
    {
        return (string) $this->name;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;


        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    public function getMobilePhone(): ?string
    {
        return $this->mobile_phone;
    }

    public function setMobilePhone(string $mobile_phone): self
    {
        $this->mobile_phone = $mobile_phone;

        return $this;
    }


    /**
     * @return DateTimeInterface|null
     */
    public function getBirthdayDate(): ?\DateTimeInterface
    {
        return $this->birthday_date;
    }


    /**
     * @param DateTimeInterface $birthday_date
     * @return $this
     */
    public function setBirthdayDate(\DateTimeInterface $birthday_date): self
    {
        $this->birthday_date = $birthday_date;

        return $this;
    }

    /**
     * Returning a salt is only needed, if you are not using a modern
     * hashing algorithm (e.g. bcrypt or sodium) in your security.yaml.
     *
     * @see UserInterface
     */
    public function getSalt(): ?string
    {
        return null;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function slugify() : string {
        $slug = new Slugify();
        return $slug->slugify($this->name);
    }

    public function getType(): ?int
    {
        return $this->type;
    }

    public function setType(int $type): self
    {
        $this->type = $type;

        return $this;
    }








    /**
     * @return Collection
     */


    public function serialize(): string
    {

        return serialize([
            $this->id,
            $this->name,
            $this->password]);

    }

    public function unserialize($data): array
    {

        return  list (
            $this->id,
            $this->name,
            $this->password
            ) =  unserialize($data,['allowed_classes' => false]);
    }

    public function getLogo(): ?string
    {
        return $this->logo;
    }

    public function setLogo(string $logo): self
    {
        $this->logo = $logo;

        return $this;
    }

    /**
     * @return string
     */
    public function getSlug(): string
    {
        $slug = new Slugify();
        return $slug->slugify($this->name);
    }

    /**
     * @return string
     */






    /**
     * @return Collection|Event[]
     */
    public function getEvents(): Collection
    {
        return $this->events;
    }

    public function addEvent(Event $event): self
    {
        if (!$this->events->contains($event)) {
            $this->events[] = $event;
            $event->setSchool($this);
        }

        return $this;
    }

    public function removeEvent(Event $event): self
    {
        if ($this->events->removeElement($event)) {
            // set the owning side to null (unless already changed)
            if ($event->getSchool() === $this) {
                $event->setSchool(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Child[]
     */
    public function getChildren(): Collection
    {
        return $this->children;
    }

    public function addChild(Child $child): self
    {
        if (!$this->children->contains($child)) {
            $this->children[] = $child;
            $child->setParent($this);
        }

        return $this;
    }

    public function removeChild(Child $child): self
    {
        if ($this->children->removeElement($child)) {
            // set the owning side to null (unless already changed)
            if ($child->getParent() === $this) {
                $child->setParent(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Child[]
     */
    public function getUsers(): Collection
    {
        return $this->users;
    }

    public function addUser(Child $user): self
    {
        if (!$this->users->contains($user)) {
            $this->users[] = $user;
            $user->setSchool($this);
        }

        return $this;
    }

    public function removeUser(Child $user): self
    {
        if ($this->users->removeElement($user)) {
            // set the owning side to null (unless already changed)
            if ($user->getSchool() === $this) {
                $user->setSchool(null);
            }
        }

        return $this;
    }

    /**
     * @return mixed
     */
    public function getFacebookID()
    {
        return $this->facebookID;
    }

    /**
     * @param mixed $facebookID
     */
    public function setFacebookID($facebookID): void
    {
        $this->facebookID = $facebookID;
    }

    /**
     * @return mixed
     */
    public function getFacebookToken()
    {
        return $this->facebookToken;
    }

    /**
     * @param mixed $facebookToken
     */
    public function setFacebookToken($facebookToken): void
    {
        $this->facebookToken = $facebookToken;
    }
}

src/Form/UserType.php
<?php

namespace App\Form;

use App\Entity\User;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\EmailType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\Extension\Core\Type\NumberType;
use Symfony\Component\Form\Extension\Core\Type\TelType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class UserType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('email',EmailType::class, [
                'label' => 'forms.email'
            ])
            ->add('logo',FileType::class,[
                'label' => 'forms.users.logo',
                'data_class' => null,

            ])

            ->add('mobile_phone', NumberType::class, [
                'label' => 'forms.mobilephone'
            ])
                ->add('name', TextType::class, [
                    'label' => 'forms.username'
                ])
            ->add('mobile_phone',TelType::class,[
                'label' => 'forms.telephone'
            ])


        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => User::class,
            'translation_domain' => "forms"

        ]);
    }
}

templates/pages/admin/users/_card.html.twig
{% trans_default_domain 'admin' %}
<div class="col-md-3">


<div class="card " style="width: 18rem;">
    {% if  user.email is defined %}
            <img src=" {{ asset('uploads/users/' ~ user.logo) }} " class="card-img-top" alt="logo">
    {% else %}
             <img src=" {{ asset('uploads/users/' ~ user.parent.logo) }}" class="card-img-top" alt="logo">
    {% endif %}
    <div class="card-body">
        <h5 class="card-title">    {{ user.name }} </h5>
        {% if  user.email is defined %}
            <span class="card-title">  {{ user.email }}</span>
        {% else %}
            <span class="card-title">  {{ user.formattedSchoolarLevel|trans({},'types') }}</span>
            <span class="card-title">  {{ user.parent.name }}</span>
        {% endif %}
    </div>

    <ul class="list-group list-group-flush">

        {% if ( ( user.type is defined) and( user.type == 1) ) or ( user.email is not defined ) %}
            <li class="list-group-item">
                <p class="card-text"> <span class="fw-bold"> {{ 'users.birthday_date'|trans }} : </span> {{ user.birthdayDate |date("d/m/Y") }} </p>
            </li>
        {% endif %}
        {% if user.email is not defined %}

            <li class="list-group-item">
                <p class="card-text"> <span class="fw-bold"> {{ 'school.name'|trans({},'messages') }} : </span>{% if user.school.name is defined %} {{ user.school.name }} {% else %} {{ 'users.school.notfound'|trans({},'admin') }}  {% endif %}</p>
            </li>
        {% endif %}




        {% if user.email is defined %}
        <li class="list-group-item">

            <a href="{{ path('admin.user.edit',{'id': user.id, 'slug': user.slug }) }}" class="btn btn-warning container-fluid mb-2">{% trans %} users.edit {% endtrans %}</a>


            <form method="post" action="{{ path('admin.user.remove',{id: user.id}) }}" onsubmit="return confirm('Are you sure ?')">
            <input type="hidden" name="_method" value="DELETE">
            <input type="hidden" name="_token" value="{{ csrf_token('remove' ~ user.id) }}">
            <button class="btn container-fluid btn-danger">{{ 'users.remove'|trans }}</button>
            </form>

        </li>
        {% endif %}

    </ul>
</div>

</div>

templates/pages/admin/users/_form.html.twig
{% trans_default_domain 'admin' %}

<div class="container lt-4">

    {{ form_start(form) }}
    <div class="row">
        <div class="col-md-4">{{ form_row(form.name) }}</div>
        <div class="col-md-4">{{ form_row(form.email) }}</div>

    </div>

    <div class="row">
        <div class="col-md-4">{{ form_row(form.mobile_phone) }}</div>
    </div>
    {{ form_rest(form) }}
    <button class="btn btn-primary"> {{ button|default('users.edit')|trans }} </button>
    {{ form_end(form ) }}

</div>

templates/pages/admin/users/admin.user.edit.html.twig
{% extends 'base.html.twig' %}

{% block title %} Admin - User Edition {% endblock %}

{% block body %}

    {{ include('pages/admin/users/_form.html.twig',{form:form}) }}

    <a href="{{ path('admin.user.edit.password',{'id': user.id,'slug': user.slug}) }}" class="btn btn-primary">
        {% trans from 'forms' %} forms.users.change.password {% endtrans %}
    </a>
{% endblock %}

templates/pages/admin/users/admin.user.edit.password.html.twig
{% trans_default_domain 'admin' %}
{% extends 'base.html.twig' %}

{% block title %} Admin - User Edition {% endblock %}

{% block body %}
    <div class="container lt-4">

        {{ form_start(form) }}
        <div class="row">
            <div class="col-md-4">{{ form_row(form.password) }}</div>
        </div>


        <button class="btn btn-primary"> {{ button|default('users.change.password')|trans }} </button>
        {{ form_end(form ) }}

    </div>


{% endblock %}

templates/pages/admin/users/admin.users.show.html.twig
{% extends 'base.html.twig' %}
{% trans_default_domain 'admin' %}

{% block title %} Panel Admin - Event {% endblock %}

{% block body %}
    {% for message in app.flashes('success') %}
        <div class="alert alert-success">{{ message }}</div>
    {% endfor %}
    <div class="container-fluid bg-light " style="padding-top: 5%">
        <div class="container  ">
            {{ form_start(search_form) }}
            <div class="row ">
                <div class="col mt-4">
                    {{ form_row(search_form.roles) }}
                </div>
                <div class="col mt-4">
                    {{ form_row(search_form.scholar_level) }}
                </div>
            </div>


            <div class="form-row align-items end">
                <div class="col ">
                    {{ form_row(search_form.type) }}
                </div>
                <div class="col">
                    {{ form_row(search_form.related_school) }}
                </div>
            </div>

            <div class=" container mt-3  text-center">
                <div class="col">
                    <button class="mb-3 btn btn-primary"> {{ 'user.filter'|trans({},'messages') }}</button>
                </div>
            </div>


            {{ form_end(search_form) }}
        </div>
    </div>



    <div class="row mb-0">
        {{ include('pages/admin/navigation_box.html.twig') }}

            <div class="col col-md-10">

                <div class="row">
                {% for user in users %}
                       <div class="col-md-3 me-5">
                           {{ include('pages/admin/users/_card.html.twig',{user:user}) }}
                       </div>
                {% endfor %}
                </div>
                <div class="pagination">
                    {{ knp_pagination_render(users) }}
                </div>
            </div>
    </div>




{% endblock %}