src/Entity/Event.php
<?php

namespace App\Entity;

use App\Repository\EventRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Intl\Locale;
use Symfony\Component\Validator\Constraints as Assert;


/**
 * @ORM\Entity(repositoryClass=EventRepository::class)
 * @UniqueEntity("name")
 */
class Event
{
    

    const STATE = [
        0 => "En Cours",
        1 => "Inscription Fermee - En attente",
        2 => "Confirme",
        3 => "Fini"
    ];


    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Type(
     *     type="string",
     *     message="event.type.string"
     * )
     */
    private $name;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Type(
     *     type="string",
     *     message="event.type.string"
     * )
     */
    private $nameAr;


    /**
     * @ORM\ManyToOne(targetEntity=Product::class, inversedBy="events")
     * @ORM\JoinColumn(nullable=true)
     * @Assert\Type(
     *     type="object",
     *     message="event.type.object.product"
     * )
     * @Assert\NotNull
     */
    private $product;





    /**
     * @ORM\Column(type="integer")
     *
     * @Assert\Type(
     *     type="integer",
     *     message="event.type.integer"
     * )
     * @Assert\NotNull
     */

    private $price;





    /**
     * @ORM\Column(type="text")
     * @Assert\Type(
     *     type="string",
     *     message="event.type.string"
     * )
     */
    private $descriptionAr;

    /**
     * @ORM\Column(type="text")
     * @Assert\Type(
     *     type="string",
     *     message="event.type.string"
     * )
     */
    private $descriptionFr;

    /**
     * @ORM\Column(type="text")
     * @Assert\Type(
     *     type="string",
     *     message="event.type.string"
     * )
     */
    private $descriptionEn;

    /**
     * @ORM\Column(type="integer")
     * @Assert\Type(
     *     type="integer",
     *     message="event.type.integer"
     * )
     * @Assert\NotNull
     */
    private $reservation_places;

    /**
     * @ORM\Column(type="integer")
     * @Assert\Type(
     *     type="integer",
     *     message="event.type.integer"
     * )
     * @Assert\NotNull
     */
    private $state;



    /**
     * @ORM\Column(type="datetime")
     * @Assert\GreaterThan("today")
     * @Assert\NotNull
     */

    private $event_datetime;

    /**
     * @ORM\Column(type="date")
     * @Assert\GreaterThan("today")
     * @Assert\NotNull
     */
    private $deadline_date;



    /**
     * @var array
     * @ORM\Column(type="array", nullable=true)
     */
    private $reservations = [];

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="events")
     * @ORM\JoinColumn(nullable=false)
     */
    private $school;





    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getProduct(): ?Product
    {
        return $this->product;
    }

    public function setProduct(?Product $product): self
    {
        $this->product = $product;

        return $this;
    }



    public function getPrice(): ?int
    {
        return $this->price;
    }

    public function setPrice(int $price): self
    {
        $this->price = $price;

        return $this;
    }







    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getReservationPlaces(): ?int
    {
        return $this->reservation_places;
    }

    public function setReservationPlaces(int $reservation_places): self
    {
        $this->reservation_places = $reservation_places;

        return $this;
    }

    public function getState(): ?int
    {
        return $this->state;
    }

    public function setState(int $state): self
    {
        $this->state = $state;

        return $this;
    }


    public function getEventDateTime(): ?\DateTimeInterface
    {
        return $this->event_datetime;
    }

    public function setEventDateTime(\DateTimeInterface $event_datetime): self
    {
        $this->event_datetime = $event_datetime;

        return $this;
    }

    public function getDeadlineDate(): ?\DateTimeInterface
    {
        return $this->deadline_date;
    }

    public function setDeadlineDate(\DateTimeInterface $deadline_date): self
    {
        $this->deadline_date = $deadline_date;

        return $this;
    }



    /**
     * @return mixed
     */
    public function getNameAr()
    {
        return $this->nameAr;
    }

    /**
     * @param mixed $nameAr
     */
    public function setNameAr($nameAr): void
    {
        $this->nameAr = $nameAr;
    }

    public function  getFormattedName() {
        $locale = Locale::getDefault();
        if (($locale == 'fr') || ($locale == 'en')) {
            return $this->name;
        } else {
            return $this->nameAr;
        }
    }

    /**
     * @return mixed
     */
    public function getDescriptionAr()
    {
        return $this->descriptionAr;
    }

    /**
     * @param mixed $descriptionAr
     */
    public function setDescriptionAr($descriptionAr): void
    {
        $this->descriptionAr = $descriptionAr;
    }

    /**
     * @return mixed
     */
    public function getDescriptionFr()
    {
        return $this->descriptionFr;
    }

    /**
     * @param mixed $descriptionFr
     */
    public function setDescriptionFr($descriptionFr): void
    {
        $this->descriptionFr = $descriptionFr;
    }

    /**
     * @return mixed
     */
    public function getDescriptionEn()
    {
        return $this->descriptionEn;
    }

    /**
     * @param mixed $descriptionEn
     */
    public function setDescriptionEn($descriptionEn): void
    {
        $this->descriptionEn = $descriptionEn;
    }

        public function getFormattedDescription() {
            $locale = Locale::getDefault();
            switch ($locale) {
                case 'en':
                    return $this->descriptionEn;
                case 'ar':
                    return $this->descriptionAr;
                default:
                    return $this->descriptionFr;
            }
        }

    /**
     * @return array|null
     */
    public function getReservations(): ?array
        {
            return $this->reservations;
        }

        public function getReservationsNumber(): int
        {
            return count($this->reservations);
        }

        public function setReservations(?array $reservations): self
        {
            $this->reservations = $reservations;

            return $this;
        }

    public function removeReservations(?int $id): self
    {
        $array = $this->reservations;
        $index = array_search($id, $array);

        if ($index != false ) {
            unset($this->reservations[$index]);
        }

        return $this;
    }


        public function addReservation(int $child_id) : self {
            array_push($this->reservations,$child_id);
            $this->reservations = array_unique($this->reservations);
            return $this;
        }

        public function getSchool(): ?User
        {
            return $this->school;
        }

        public function setSchool(?User $school): self
        {
            $this->school = $school;

            return $this;
        }

}

src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Cocur\Slugify\Slugify;
use DateTimeInterface;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass=UserRepository::class)
 * @UniqueEntity("email")
 */
class User extends AbstractLocalisation implements UserInterface
{


   /* const ROLES = [
        "roles.superadministrator" => ["ROLE_SUPER_ADMIN","ROLE_ADMIN","ROLE_MODERATOR"],
        "roles.administrator" => ["ROLE_ADMIN","ROLE_MODERATOR"],
        "roles.moderator" => ["ROLE_MODERATOR","ROLE_USER"] ,
        "roles.user" => ["ROLE_USER"],
    ];*/

    const ROLES = [
        "roles.superadministrator" => "ROLE_SUPER_ADMIN",
        "roles.administrator" => "ROLE_ADMIN",
        "roles.moderator" => "ROLE_MODERATOR" ,
        "roles.user" => "ROLE_USER",
    ];

    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     * @Assert\Email(
     *     message="user.type.emails"
     * )
     *
     */
    private $email;

    /**
     * @ORM\Column(type="json")
     */
    private $roles = [];

    /**
     * @ORM\Column(type="string", length=255)
     * @var string The hashed password
     * @Assert\NotCompromisedPassword(
     *     message="user.type.password.compromised"
     *  )
     */
    private $password;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Regex(
     *     pattern="/\d{9}/",
     *     message="user.type.regex.mobilephone"
     * )
     */
    private $mobile_phone;

    /**
     * @ORM\Column(type="date", nullable=true)
     */
    private $birthday_date;



    /**
     * @ORM\Column(type="string", length=255)
     *
     */
    private $name;

    /**
     * @ORM\Column(type="string", length=255,nullable=true)
     *
     */
    private $facebookID;

    /**
     * @ORM\Column(type="string", length=255,nullable=true)
     *
     */
    private $facebookToken;

    /**
     * @ORM\Column(type="integer")
     * @Assert\Type(
     *     type="integer",
     *     message="user.type.integer"
     * )
     */
    private $type;





    /**
     * @ORM\Column(type="string", length=255)
     */
    private $logo;


    /**
     * @ORM\OneToMany(targetEntity=Event::class, mappedBy="school")
     */
    private $events;

    /**
     * @ORM\OneToMany(targetEntity=Child::class, mappedBy="parent")
     */
    private $children;

    /**
     * @ORM\OneToMany(targetEntity=Child::class, mappedBy="school")
     */
    private $users;


    public function __construct()
    {




        $this->events = new ArrayCollection();
        $this->children = new ArrayCollection();
        $this->users = new ArrayCollection();
    }


    public function getId(): ?int
    {
        return $this->id;
    }

    /**
     *
     *
     * @see UserInterface
     */
    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }


    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUsername(): string
    {
        return (string) $this->name;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;


        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    public function getMobilePhone(): ?string
    {
        return $this->mobile_phone;
    }

    public function setMobilePhone(string $mobile_phone): self
    {
        $this->mobile_phone = $mobile_phone;

        return $this;
    }


    /**
     * @return DateTimeInterface|null
     */
    public function getBirthdayDate(): ?\DateTimeInterface
    {
        return $this->birthday_date;
    }


    /**
     * @param DateTimeInterface $birthday_date
     * @return $this
     */
    public function setBirthdayDate(\DateTimeInterface $birthday_date): self
    {
        $this->birthday_date = $birthday_date;

        return $this;
    }

    /**
     * Returning a salt is only needed, if you are not using a modern
     * hashing algorithm (e.g. bcrypt or sodium) in your security.yaml.
     *
     * @see UserInterface
     */
    public function getSalt(): ?string
    {
        return null;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function slugify() : string {
        $slug = new Slugify();
        return $slug->slugify($this->name);
    }

    public function getType(): ?int
    {
        return $this->type;
    }

    public function setType(int $type): self
    {
        $this->type = $type;

        return $this;
    }








    /**
     * @return Collection
     */


    public function serialize(): string
    {

        return serialize([
            $this->id,
            $this->name,
            $this->password]);

    }

    public function unserialize($data): array
    {

        return  list (
            $this->id,
            $this->name,
            $this->password
            ) =  unserialize($data,['allowed_classes' => false]);
    }

    public function getLogo(): ?string
    {
        return $this->logo;
    }

    public function setLogo(string $logo): self
    {
        $this->logo = $logo;

        return $this;
    }

    /**
     * @return string
     */
    public function getSlug(): string
    {
        $slug = new Slugify();
        return $slug->slugify($this->name);
    }

    /**
     * @return string
     */






    /**
     * @return Collection|Event[]
     */
    public function getEvents(): Collection
    {
        return $this->events;
    }

    public function addEvent(Event $event): self
    {
        if (!$this->events->contains($event)) {
            $this->events[] = $event;
            $event->setSchool($this);
        }

        return $this;
    }

    public function removeEvent(Event $event): self
    {
        if ($this->events->removeElement($event)) {
            // set the owning side to null (unless already changed)
            if ($event->getSchool() === $this) {
                $event->setSchool(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Child[]
     */
    public function getChildren(): Collection
    {
        return $this->children;
    }

    public function addChild(Child $child): self
    {
        if (!$this->children->contains($child)) {
            $this->children[] = $child;
            $child->setParent($this);
        }

        return $this;
    }

    public function removeChild(Child $child): self
    {
        if ($this->children->removeElement($child)) {
            // set the owning side to null (unless already changed)
            if ($child->getParent() === $this) {
                $child->setParent(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Child[]
     */
    public function getUsers(): Collection
    {
        return $this->users;
    }

    public function addUser(Child $user): self
    {
        if (!$this->users->contains($user)) {
            $this->users[] = $user;
            $user->setSchool($this);
        }

        return $this;
    }

    public function removeUser(Child $user): self
    {
        if ($this->users->removeElement($user)) {
            // set the owning side to null (unless already changed)
            if ($user->getSchool() === $this) {
                $user->setSchool(null);
            }
        }

        return $this;
    }

    /**
     * @return mixed
     */
    public function getFacebookID()
    {
        return $this->facebookID;
    }

    /**
     * @param mixed $facebookID
     */
    public function setFacebookID($facebookID): void
    {
        $this->facebookID = $facebookID;
    }

    /**
     * @return mixed
     */
    public function getFacebookToken()
    {
        return $this->facebookToken;
    }

    /**
     * @param mixed $facebookToken
     */
    public function setFacebookToken($facebookToken): void
    {
        $this->facebookToken = $facebookToken;
    }
}

templates/pages/about-us.html.twig
{% extends 'base.html.twig' %}

{% block title %} Qui Sommes-Nous {% endblock %}

{% block body %}

    <h5 class="mt-4">About Us</h5>

    <p>
        Lorem ipsul malor
    </p>
{% endblock %}

templates/pages/contact.html.twig
{% extends 'base.html.twig' %}

{% block  title %} Contact {% endblock %}

{% block body %}

    <h5 class="mt-4">Contact</h5>


{% endblock %}

templates/pages/home1.html.twig
{% extends 'base.html.twig' %}


{% block title %} Acceuil {% endblock %}

{% block body %}



        {% for message in app.flashes('success') %}
            <div class="alert alert-success">{{ message }}</div>
        {% endfor %}



        <div id="myCarousel" class="carousel slide carousel-fade mb-5" data-bs-ride="carousel">
            <div class="carousel-indicators">
                <button type="button" data-bs-target="#myCarousel" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
                <button type="button" data-bs-target="#myCarousel" data-bs-slide-to="1" aria-label="Slide 2"></button>
                <button type="button" data-bs-target="#myCarousel" data-bs-slide-to="2" aria-label="Slide 3"></button>
            </div>
            <div class="carousel-inner">
                <div class="carousel-item active">
                    <img class="bd-placeholder-img" width="100%" height="100%" src="{{ asset('slide_home_1.png','slides') }}" aria-hidden="true" >

                    <div class="container">
                        <div class="carousel-caption text-start">
                            <p class="text-center" ><a class="btn btn-lg btn-primary" href="#"> TO CHANGE </a></p>
                        </div>
                    </div>
                </div>
                <div class="carousel-item">
                    <img class="bd-placeholder-img" width="100%" height="100%" src="{{ asset('slide_home_2.png','slides') }}" aria-hidden="true" >

                    <div class="container">
                        <div class="carousel-caption">
                            <p class="text-center"><a class="btn btn-lg btn-primary" href="#">TO CHANGE</a></p>
                        </div>
                    </div>
                </div>

            </div>
            <button class="carousel-control-prev" type="button" data-bs-target="#myCarousel" data-bs-slide="prev">
                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                <span class="visually-hidden">Previous</span>
            </button>
            <button class="carousel-control-next" type="button" data-bs-target="#myCarousel" data-bs-slide="next">
                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                <span class="visually-hidden">Next</span>
            </button>
        </div>


        <div class="container mt-5 w-50 p-3 mb-5">
            <div class="text-center ">
                <h2 >Qui Sommes-Nous</h2>
                <p >
                    Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.
                </p>
            </div>
        </div>






    <div class="container-fluid pb-5" style="background-color: #0000FF" >
    <div class="container "  >

        <h2 class="text-center" style="color: white">Nos Services</h2>

        <div id="carouselProducts" class="carousel slide  " data-bs-ride="carousel">
            <div class="carousel-inner ">
                {% set index = 0 %}
                {% for slide in products %}

                 <div class="container carousel-item {% if index == 0 %} {% set index = 1%} active {% endif %}">

                    <div class="row justify-content-center">
                        {% for product in slide %}
                        {% if product is defined %}
                            <div class="col col-md-auto"  >
                                    <div class="card  " style="width: 18rem;">
                                        <img src="{% if asset_exists('uploads/products/' ~ product.coverImage) %} {{ asset('uploads/products/' ~ product.coverImage) }} {% else %} {{ asset('uploads/products/sample_product.png') }} {% endif %}" class="card-img-top" alt="...">
                                        <div class="card-body">
                                            <a type="button" class="btn w-100" style="color: white;background-color: #985FAB" href="{{ path('user.product',{id:product.id}) }}"> {{ 'message.know_more'|trans({},'messages') }}   </a>
                                        </div>
                                    </div>
                            </div>
                            {% endif %}
                        {% endfor %}
                    </div>
                </div>
                {% endfor %}

            <button class="carousel-control-prev" type="button" data-bs-target="#carouselProducts" data-bs-slide="prev">
                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                <span class="visually-hidden">Previous</span>
            </button>
            <button class="carousel-control-next" type="button" data-bs-target="#carouselProducts" data-bs-slide="next">
                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                <span class="visually-hidden">Next</span>
            </button>

        </div>


    </div>

    </div>
    </div>


    <div class="container-fluid pb-5" style="background-color: #DDE8FE">
    <div class="container">

        <h2 class="text-center" style="color: white">Nos Programmes</h2>

        <div id="carouselEvents" class="carousel slide carousel-fade" data-bs-ride="carousel">
            <div class="carousel-inner">
                {% set index = 0 %}
                {% for slide in events %}
                 <div class="container carousel-item {% if index == 0 %} {% set index = 1%} active {% endif %}">

                    <div class="row justify-content-center">
                        {% for event in slide %}
                        {% if event is defined %}

                            <div class="col col-md-auto" >

                                    <div class="card  " style="width: 18rem;">
                                        <img src="{% if asset_exists('uploads/products/' ~ event.product.coverImage) %} {{ asset('uploads/products/' ~ event.product.coverImage) }} {% else %} {{ asset('uploads/products/sample_product.png') }} {% endif %}" class="card-img-top" alt="...">
                                        <div class="card-body">
                                        <p style="color: black;">
                                             Date : {{ event.eventdatetime|date("m/d/Y") }} <br>
                                             Ecole : {{ event.school.name }}
                                        </p>
                                                <a type="button" class=" btn w-100" style="color: white;background-color: #985FAB" href="{{ path('user.reserve',{'id': event.id}) }}">  Reserve  </a>
                                        </div>
                                    </div>
                            </div>
                            {% endif %}
                        {% endfor %}
                    </div>
                </div>
                {% endfor %}

            <button class="carousel-control-prev" type="button" data-bs-target="#carouselEvents" data-bs-slide="prev">
                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                <span class="visually-hidden">Previous</span>
            </button>
            <button class="carousel-control-next" type="button" data-bs-target="#carouselEvents" data-bs-slide="next">
                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                <span class="visually-hidden">Next</span>
            </button>

        </div>
        </div>
    </div>
    </div>

















































{% endblock %}

templates/pages/product.html.twig
{% extends 'base.html.twig' %}

{% block title %}Log in!{% endblock %}
{% trans_default_domain 'forms' %}

{% block body %}

    <div class="container mt-4">

        <h2> Product Presentation</h2>

        <div class="container-fluid">
            <img class="text-center" src="{% if asset_exists('uploads/products/' ~ product.coverImage) %} {{ asset('uploads/products/' ~ product.coverImage) }} {% else %} {{ asset('uploads/products/sample_product.png') }} {% endif %}">
            <h3>{{ product.formattedName }}</h3>
            <p>
                {{ product.formattedDescription }}
            </p>
        </div>

    </div>

{% endblock %}

templates/pages/reservation.html.twig
{% extends 'base.html.twig' %}

{% block title %}Log in!{% endblock %}
{% trans_default_domain 'forms' %}

{% block body %}

    <div class="container mt-4">

        <h2> Event Presentation </h2>

        <div class="container-fluid">
            <img class="text-center" src="{% if asset_exists('uploads/products/' ~ event.product.coverImage) %} {{ asset('uploads/products/' ~ event.product.coverImage) }} {% else %} {{ asset('uploads/products/sample_product.png') }} {% endif %}">
            <h3>{{ event.formattedName }}</h3>
            <h5>Price : {{ event.price }}</h5>
            <h5>Places : {{ event.reservationPlaces }}</h5>
            <h5>Date de l'evenement : {{ event.eventDatetime|date('d/m/y') }}</h5>
            <h5>Date de fin d'inscription : {{ event.deadlineDate|date('d/m/y') }}</h5>
            <p>
                {{ event.formattedDescription }}
            </p>
        </div>
        
        


        <form method="post" class="mt-4">
            {% for message in app.flashes('success') %}
                <div class="alert alert-success">{{ message }}</div>
            {% endfor %}

            {% if error is defined %}
                <div class="alert alert-danger">{{ error.messageKey|trans(error.messageData, 'security')  }}</div>
            {% endif %}

        <div class="container">
            {{ form_start(form) }}
                    {{ form_row(form.choices) }}
            <button class="btn-primary btn">
                {{ 'event.reserve'|trans({},'messages') }}
            </button>
            {{ form_end(form) }}
        </div>



        </form>
    </div>

{% endblock %}

templates/pages/under_construction.html.twig
{% extends 'base.html.twig' %}

{% block  title %} Contact {% endblock %}

{% block body %}

    <h5 class="mt-4">Under Construction</h5>

    <form method="post">

        {% for message in app.flashes('success') %}
            <div class="alert alert-success">{{ message }}</div>
        {% endfor %}

        {% if error is defined %}
            <div class="alert alert-danger">{{ error.messageKey|trans(error.messageData, 'security')  }}</div>
        {% endif %}

        <div class="container">
            {{ form_start(form) }}

            {{ form_row(form.email) }}
            {{ form_row(form.firstName) }}
            {{ form_row(form.familyName) }}
            {{ form_row(form.mobilePhone) }}
            {{ form_row(form.buisenessName) }}
            <button class="btn-primary btn">
                {{ 'message.catalog.download'|trans() }}
            </button>
            {{ form_end(form) }}
        </div>



    </form>

{% endblock %}