src/Entity/Event.php
<?php

namespace App\Entity;

use App\Repository\EventRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Intl\Locale;
use Symfony\Component\Validator\Constraints as Assert;


/**
 * @ORM\Entity(repositoryClass=EventRepository::class)
 * @UniqueEntity("name")
 */
class Event
{
    

    const STATE = [
        0 => "En Cours",
        1 => "Inscription Fermee - En attente",
        2 => "Confirme",
        3 => "Fini"
    ];


    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Type(
     *     type="string",
     *     message="event.type.string"
     * )
     */
    private $name;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Type(
     *     type="string",
     *     message="event.type.string"
     * )
     */
    private $nameAr;


    /**
     * @ORM\ManyToOne(targetEntity=Product::class, inversedBy="events")
     * @ORM\JoinColumn(nullable=true)
     * @Assert\Type(
     *     type="object",
     *     message="event.type.object.product"
     * )
     * @Assert\NotNull
     */
    private $product;





    /**
     * @ORM\Column(type="integer")
     *
     * @Assert\Type(
     *     type="integer",
     *     message="event.type.integer"
     * )
     * @Assert\NotNull
     */

    private $price;





    /**
     * @ORM\Column(type="text")
     * @Assert\Type(
     *     type="string",
     *     message="event.type.string"
     * )
     */
    private $descriptionAr;

    /**
     * @ORM\Column(type="text")
     * @Assert\Type(
     *     type="string",
     *     message="event.type.string"
     * )
     */
    private $descriptionFr;

    /**
     * @ORM\Column(type="text")
     * @Assert\Type(
     *     type="string",
     *     message="event.type.string"
     * )
     */
    private $descriptionEn;

    /**
     * @ORM\Column(type="integer")
     * @Assert\Type(
     *     type="integer",
     *     message="event.type.integer"
     * )
     * @Assert\NotNull
     */
    private $reservation_places;

    /**
     * @ORM\Column(type="integer")
     * @Assert\Type(
     *     type="integer",
     *     message="event.type.integer"
     * )
     * @Assert\NotNull
     */
    private $state;



    /**
     * @ORM\Column(type="datetime")
     * @Assert\GreaterThan("today")
     * @Assert\NotNull
     */

    private $event_datetime;

    /**
     * @ORM\Column(type="date")
     * @Assert\GreaterThan("today")
     * @Assert\NotNull
     */
    private $deadline_date;



    /**
     * @var array
     * @ORM\Column(type="array", nullable=true)
     */
    private $reservations = [];

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="events")
     * @ORM\JoinColumn(nullable=false)
     */
    private $school;





    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getProduct(): ?Product
    {
        return $this->product;
    }

    public function setProduct(?Product $product): self
    {
        $this->product = $product;

        return $this;
    }



    public function getPrice(): ?int
    {
        return $this->price;
    }

    public function setPrice(int $price): self
    {
        $this->price = $price;

        return $this;
    }







    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getReservationPlaces(): ?int
    {
        return $this->reservation_places;
    }

    public function setReservationPlaces(int $reservation_places): self
    {
        $this->reservation_places = $reservation_places;

        return $this;
    }

    public function getState(): ?int
    {
        return $this->state;
    }

    public function setState(int $state): self
    {
        $this->state = $state;

        return $this;
    }


    public function getEventDateTime(): ?\DateTimeInterface
    {
        return $this->event_datetime;
    }

    public function setEventDateTime(\DateTimeInterface $event_datetime): self
    {
        $this->event_datetime = $event_datetime;

        return $this;
    }

    public function getDeadlineDate(): ?\DateTimeInterface
    {
        return $this->deadline_date;
    }

    public function setDeadlineDate(\DateTimeInterface $deadline_date): self
    {
        $this->deadline_date = $deadline_date;

        return $this;
    }



    /**
     * @return mixed
     */
    public function getNameAr()
    {
        return $this->nameAr;
    }

    /**
     * @param mixed $nameAr
     */
    public function setNameAr($nameAr): void
    {
        $this->nameAr = $nameAr;
    }

    public function  getFormattedName() {
        $locale = Locale::getDefault();
        if (($locale == 'fr') || ($locale == 'en')) {
            return $this->name;
        } else {
            return $this->nameAr;
        }
    }

    /**
     * @return mixed
     */
    public function getDescriptionAr()
    {
        return $this->descriptionAr;
    }

    /**
     * @param mixed $descriptionAr
     */
    public function setDescriptionAr($descriptionAr): void
    {
        $this->descriptionAr = $descriptionAr;
    }

    /**
     * @return mixed
     */
    public function getDescriptionFr()
    {
        return $this->descriptionFr;
    }

    /**
     * @param mixed $descriptionFr
     */
    public function setDescriptionFr($descriptionFr): void
    {
        $this->descriptionFr = $descriptionFr;
    }

    /**
     * @return mixed
     */
    public function getDescriptionEn()
    {
        return $this->descriptionEn;
    }

    /**
     * @param mixed $descriptionEn
     */
    public function setDescriptionEn($descriptionEn): void
    {
        $this->descriptionEn = $descriptionEn;
    }

        public function getFormattedDescription() {
            $locale = Locale::getDefault();
            switch ($locale) {
                case 'en':
                    return $this->descriptionEn;
                case 'ar':
                    return $this->descriptionAr;
                default:
                    return $this->descriptionFr;
            }
        }

    /**
     * @return array|null
     */
    public function getReservations(): ?array
        {
            return $this->reservations;
        }

        public function getReservationsNumber(): int
        {
            return count($this->reservations);
        }

        public function setReservations(?array $reservations): self
        {
            $this->reservations = $reservations;

            return $this;
        }

    public function removeReservations(?int $id): self
    {
        $array = $this->reservations;
        $index = array_search($id, $array);

        if ($index != false ) {
            unset($this->reservations[$index]);
        }

        return $this;
    }


        public function addReservation(int $child_id) : self {
            array_push($this->reservations,$child_id);
            $this->reservations = array_unique($this->reservations);
            return $this;
        }

        public function getSchool(): ?User
        {
            return $this->school;
        }

        public function setSchool(?User $school): self
        {
            $this->school = $school;

            return $this;
        }

}

src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Cocur\Slugify\Slugify;
use DateTimeInterface;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass=UserRepository::class)
 * @UniqueEntity("email")
 */
class User extends AbstractLocalisation implements UserInterface
{


   /* const ROLES = [
        "roles.superadministrator" => ["ROLE_SUPER_ADMIN","ROLE_ADMIN","ROLE_MODERATOR"],
        "roles.administrator" => ["ROLE_ADMIN","ROLE_MODERATOR"],
        "roles.moderator" => ["ROLE_MODERATOR","ROLE_USER"] ,
        "roles.user" => ["ROLE_USER"],
    ];*/

    const ROLES = [
        "roles.superadministrator" => "ROLE_SUPER_ADMIN",
        "roles.administrator" => "ROLE_ADMIN",
        "roles.moderator" => "ROLE_MODERATOR" ,
        "roles.user" => "ROLE_USER",
    ];

    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     * @Assert\Email(
     *     message="user.type.emails"
     * )
     *
     */
    private $email;

    /**
     * @ORM\Column(type="json")
     */
    private $roles = [];

    /**
     * @ORM\Column(type="string", length=255)
     * @var string The hashed password
     * @Assert\NotCompromisedPassword(
     *     message="user.type.password.compromised"
     *  )
     */
    private $password;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Regex(
     *     pattern="/\d{9}/",
     *     message="user.type.regex.mobilephone"
     * )
     */
    private $mobile_phone;

    /**
     * @ORM\Column(type="date", nullable=true)
     */
    private $birthday_date;



    /**
     * @ORM\Column(type="string", length=255)
     *
     */
    private $name;

    /**
     * @ORM\Column(type="string", length=255,nullable=true)
     *
     */
    private $facebookID;

    /**
     * @ORM\Column(type="string", length=255,nullable=true)
     *
     */
    private $facebookToken;

    /**
     * @ORM\Column(type="integer")
     * @Assert\Type(
     *     type="integer",
     *     message="user.type.integer"
     * )
     */
    private $type;





    /**
     * @ORM\Column(type="string", length=255)
     */
    private $logo;


    /**
     * @ORM\OneToMany(targetEntity=Event::class, mappedBy="school")
     */
    private $events;

    /**
     * @ORM\OneToMany(targetEntity=Child::class, mappedBy="parent")
     */
    private $children;

    /**
     * @ORM\OneToMany(targetEntity=Child::class, mappedBy="school")
     */
    private $users;


    public function __construct()
    {




        $this->events = new ArrayCollection();
        $this->children = new ArrayCollection();
        $this->users = new ArrayCollection();
    }


    public function getId(): ?int
    {
        return $this->id;
    }

    /**
     *
     *
     * @see UserInterface
     */
    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }


    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUsername(): string
    {
        return (string) $this->name;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;


        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    public function getMobilePhone(): ?string
    {
        return $this->mobile_phone;
    }

    public function setMobilePhone(string $mobile_phone): self
    {
        $this->mobile_phone = $mobile_phone;

        return $this;
    }


    /**
     * @return DateTimeInterface|null
     */
    public function getBirthdayDate(): ?\DateTimeInterface
    {
        return $this->birthday_date;
    }


    /**
     * @param DateTimeInterface $birthday_date
     * @return $this
     */
    public function setBirthdayDate(\DateTimeInterface $birthday_date): self
    {
        $this->birthday_date = $birthday_date;

        return $this;
    }

    /**
     * Returning a salt is only needed, if you are not using a modern
     * hashing algorithm (e.g. bcrypt or sodium) in your security.yaml.
     *
     * @see UserInterface
     */
    public function getSalt(): ?string
    {
        return null;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function slugify() : string {
        $slug = new Slugify();
        return $slug->slugify($this->name);
    }

    public function getType(): ?int
    {
        return $this->type;
    }

    public function setType(int $type): self
    {
        $this->type = $type;

        return $this;
    }








    /**
     * @return Collection
     */


    public function serialize(): string
    {

        return serialize([
            $this->id,
            $this->name,
            $this->password]);

    }

    public function unserialize($data): array
    {

        return  list (
            $this->id,
            $this->name,
            $this->password
            ) =  unserialize($data,['allowed_classes' => false]);
    }

    public function getLogo(): ?string
    {
        return $this->logo;
    }

    public function setLogo(string $logo): self
    {
        $this->logo = $logo;

        return $this;
    }

    /**
     * @return string
     */
    public function getSlug(): string
    {
        $slug = new Slugify();
        return $slug->slugify($this->name);
    }

    /**
     * @return string
     */






    /**
     * @return Collection|Event[]
     */
    public function getEvents(): Collection
    {
        return $this->events;
    }

    public function addEvent(Event $event): self
    {
        if (!$this->events->contains($event)) {
            $this->events[] = $event;
            $event->setSchool($this);
        }

        return $this;
    }

    public function removeEvent(Event $event): self
    {
        if ($this->events->removeElement($event)) {
            // set the owning side to null (unless already changed)
            if ($event->getSchool() === $this) {
                $event->setSchool(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Child[]
     */
    public function getChildren(): Collection
    {
        return $this->children;
    }

    public function addChild(Child $child): self
    {
        if (!$this->children->contains($child)) {
            $this->children[] = $child;
            $child->setParent($this);
        }

        return $this;
    }

    public function removeChild(Child $child): self
    {
        if ($this->children->removeElement($child)) {
            // set the owning side to null (unless already changed)
            if ($child->getParent() === $this) {
                $child->setParent(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Child[]
     */
    public function getUsers(): Collection
    {
        return $this->users;
    }

    public function addUser(Child $user): self
    {
        if (!$this->users->contains($user)) {
            $this->users[] = $user;
            $user->setSchool($this);
        }

        return $this;
    }

    public function removeUser(Child $user): self
    {
        if ($this->users->removeElement($user)) {
            // set the owning side to null (unless already changed)
            if ($user->getSchool() === $this) {
                $user->setSchool(null);
            }
        }

        return $this;
    }

    /**
     * @return mixed
     */
    public function getFacebookID()
    {
        return $this->facebookID;
    }

    /**
     * @param mixed $facebookID
     */
    public function setFacebookID($facebookID): void
    {
        $this->facebookID = $facebookID;
    }

    /**
     * @return mixed
     */
    public function getFacebookToken()
    {
        return $this->facebookToken;
    }

    /**
     * @param mixed $facebookToken
     */
    public function setFacebookToken($facebookToken): void
    {
        $this->facebookToken = $facebookToken;
    }
}

templates/pages/admin/_card.html.twig
{% trans_default_domain 'admin' %}
<div class="card" style="width: 18rem;">
{#    <img src="{% if asset_exists('uploads/products/' ~ event.product.logo) %} {{ asset('uploads/products/' ~ event.product.logo) }} {% else %} {{ asset('uploads/products/sample_product.png') }} {% endif %}" class="card-img-top" alt="logo">#}
        <img src="{{ asset('uploads/products/sample_product.png') }}" class="card-img-top" alt="logo">

    <div class="card-body">
        <h5 class="card-title">  {% trans %} events.school.name {% endtrans %} :  {{ event.school.name }}</h5>
{#        <h5 class="card-title">  {% trans %} events.name {% endtrans %} :  {{ event.formattedName }}</h5>#}
        <p class="card-text"> {{ (event.formattedDescription |length > 50 ? event.formattedDescription|slice(0, 140) ~ '...' : event.formattedDescription )|nl2br }}</p>
    </div>
    <ul class="list-group list-group-flush">
        <li class="list-group-item">
            {% trans %} events.limit.event_date {% endtrans %} : {{ event.eventDateTime |date("d/m/Y") }}
        </li>
        <li class="list-group-item">
            {% trans %} events.limit.deadline_date {% endtrans %} : {{ event.DeadLineDate  |date("d/m/Y") }}
        </li>

        <li class="list-group-item">
            <small class="text-muted">{% trans %} events.reservations {% endtrans %} : {{ event.reservationsNumber }} </small>
        </li>

        <li class="list-group-item">
            <a href="{{ path('admin.event.edit',{'id': event.id}) }}" class="btn btn-warning container-fluid mb-2">{% trans %} events.edit {% endtrans %}</a>
            <form method="post" action="{{ path('admin.event.remove',{id: event.id}) }}" onsubmit="return confirm('Are you sure ?')">
                <input type="hidden" name="_method" value="DELETE">
                <input type="hidden" name="_token" value="{{ csrf_token('remove' ~ event.id) }}">
                <button class="btn btn-danger container-fluid">{{ 'events.remove'|trans }}</button>
            </form>

        </li>

    </ul>
</div>

templates/pages/admin/_form.html.twig
{% trans_default_domain 'admin' %}

<div class="container lt-4">
    {{ form_start(form) }}

    <div class="row">
        <div class="col-md-4">{{ form_row(form.nameAr) }}</div>
        <div class="col-md-4">{{ form_row(form.name) }}</div>

    </div>

    <div class="row">
        <div class="col-md-4">
            {{ form_row(form.price) }}
        </div>
        <div class="col-md-4">{{ form_row(form.reservation_places) }}</div>
    </div>

    <div class="row">
        <div class="col-md-4">{{ form_row(form.event_datetime) }}</div>
        <div class="col-md-4">{{ form_row(form.deadline_date) }}</div>
    </div>

    <div class="row">
        <div class="col-md-3">{{ form_row(form.product) }}</div>
        <div class="col-md-3">{{ form_row(form.school) }}</div>
        <div class="col-md-3">{{ form_row(form.state) }}</div>
    </div>

    <div class="row">
        <div class="col-md-4">{{ form_row(form.descriptionAr) }}</div>
        <div class="col-md-4">{{ form_row(form.descriptionFr) }}</div>
        <div class="col-md-4">{{ form_row(form.descriptionEn) }}</div>
    </div>

        <button class="btn btn-primary"> {{ button|default('events.create')|trans }} </button>
    {{ form_end(form) }}
</div>

templates/pages/admin/admin.catalogs.show.html.twig
{% extends 'base.html.twig' %}

{% block title %}   Admin Panel - Edit {% endblock %}

{% block body %}
    <div class="container mt-4">
        <a href="{{ path('admin.catalogs.download') }}"> {{ 'forms.downloadForms'|trans({},'forms') }}</a>
        <table class="table">
            <thead>
            <tr>
                <th scope="col">{{ 'forms.name'|trans({},'forms') }}</th>
                <th scope="col">{{ 'forms.email'|trans({},'forms') }}</th>
                <th scope="col">{{ 'forms.mobilephone'|trans({},'forms') }}</th>
            </tr>
            </thead>
            <tbody>
            {% for catalog in catalogs %}
                {% if catalog is defined %}
                    <tr>
                        <td>{{ catalog.name }}</td>
                        <td>{{ catalog.email }}</td>
                        <td>0{{ catalog.mobilePhone }}</td>
                    </tr>
                {% endif %}
            {% endfor %}
            </tbody>
        </table>


    </div>


{% endblock %}

templates/pages/admin/admin.event.create.html.twig
{% extends 'base.html.twig' %}

{% block title %}   Admin Panel - Create  {% endblock %}

{% block body %}
    {{ include('pages/admin/_form.html.twig', {form: form,button: 'events.create'})  }}

{% endblock %}

templates/pages/admin/admin.event.edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}   Admin Panel - Edit {% endblock %}

{% block body %}
    {{ include('pages/admin/_form.html.twig', {form: form,button: 'events.edit'})  }}




    <div class="container mt-4">

        <a href="{{ path('admin.download.children.list.event',{'id': event_id } ) }}" class="col btn btn-warning mb-2"> {{  'child.download'| trans({},'messages') }}</a>


        <table class="table">
            <thead>
            <tr>
                <th scope="col">{{ 'child.name'|trans({},'messages') }}</th>
                <th scope="col">{{ 'child.school_level'|trans({},'messages') }}</th>
                <th scope="col">{{ 'child.school'|trans({},'messages') }}</th>

            </tr>
            </thead>
            <tbody>
            {% for child in childrens %}
                {% if child is defined %}
                <tr>
                    <td>{% if child.name is defined %} {{ child.name }} {% else %} {{ 'child.notfound'|trans({},'messages') }} {% endif %}</td>
                    <td>{% if child.FormattedSchoolarLevel is defined %} {{ child.FormattedSchoolarLevel|trans({},'types') }} {% else %} {{ 'child.shool_level.notfound'|trans({},'messages') }} {% endif %}</td>
                    <td></td>
                    <td>{% if child.school.name is defined %} {{ child.school.name }} {% else %} {{ 'school.notfound'|trans({},'messages') }} {% endif %}</td>
                </tr>
                {% endif %}
            {% endfor %}
            </tbody>
        </table>


    </div>


{% endblock %}

templates/pages/admin/admin.events.show.html.twig
{% extends 'base.html.twig' %}
{% trans_default_domain 'admin' %}

{% block title %} Panel Admin - Event {% endblock %}

{% block body %}
    {% for message in app.flashes('success') %}
        <div class="alert alert-success">{{ message }}</div>
    {% endfor %}

        <div class="container-fluid bg-light ">
            <div class="container  ">
            {{ form_start(search_form) }}
            <div class="row ">
                <div class="col mt-4">
                    {{ form_row(search_form.product) }}
                </div>
                <div class="col mt-4">
                    {{ form_row(search_form.school) }}
                </div>
                <div class="col mt-4">
                    {{ form_row(search_form.state) }}
                </div>
                </div>


            <div class="form-row align-items end">
                <div class="col">
                    {{ form_row(search_form.deadline_date) }}
                </div>
                <div class="col">
                    {{ form_row(search_form.event_datetime) }}
                </div>
            </div>

            <div class=" container mt-3  text-center">
                <div class="col">
                    <button class="mb-3 btn btn-primary">{{ 'messages.search'|trans({},'forms') }}</button>
                </div>
            </div>


            {{ form_end(search_form) }}
            </div>
        </div>


    <div class="mt-4 mb-4 text-center">
{#        <div class="fs-bold">{% set count = (confirmed_events|length) +  (still_events|length)  + (waiting_events|length) %} Evenement actifs : {{ count }}</div>#}
        <a href="{{ path('admin.event.create') }}" class="btn btn-primary">{% trans %} events.create {% endtrans %}</a>
    </div>



        <div class="row">
            {{ include('pages/admin/navigation_box.html.twig') }}

        <div class="col-md-10">
            <div class="row">
                {% for event in events %}

                <div class="col-md-3 me-5">
                        {{ include('pages/admin/_card.html.twig',{event:event}) }}
                </div>
                {% endfor %}
            </div>

            <div class="pagination">
                {{ knp_pagination_render(events) }}
            </div>
        </div>



{% endblock %}

templates/pages/admin/navigation_box.html.twig
<div class="col col-md-2" >
    <ul class="nav flex-column">
{#        <li class="nav-item">#}
{#            <a class="nav-link active" aria-current="page" href="{{ path('admin.events.show') }}">{% trans from 'admin' %} nav.events {% endtrans %}</a>#}
{#        </li>#}

        <li class="nav-item">
            <a class="nav-link" href="{{ path('admin.users.show') }}">{% trans from 'admin' %} nav.users {% endtrans %}</a>
        </li>

        <li class="nav-item">
            <a class="nav-link" href="{{ path('admin.products.show') }}">{% trans from 'admin' %} nav.products {% endtrans %}</a>
        </li>


{#        <li class="nav-item">#}
{#            <a class="nav-link " href="{{ path('admin.catalogs.show') }}" tabindex="-1" aria-disabled="true">{% trans from 'admin' %} nav.catalogs {% endtrans %}</a>#}
{#        </li>#}

    </ul>
</div>